### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by lindemeier** [PrismPipeline/QuiltiX#47]
Hey there,

my setup:

- Python 3.10.8
- QuilitX Version 0.5.0 from PyPI
- Ubuntu 22.04
- USD v23.02 self compiled with MaterialX, pyside6
- hdCycles and hdRpr in plugin path

When I start QuiltiX:
```bash
python -m QuiltiX 
```
I get the following error:
```bash
Traceback (most recent call last):
  File "/home/username/miniconda3/envs/usd/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/username/miniconda3/envs/usd/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/username/miniconda3/envs/usd/lib/python3.10/site-packages/QuiltiX/__main__.py", line 4, in <module>
    quiltix.launch()
  File "/home/username/miniconda3/envs/usd/lib/python3.10/site-packages/QuiltiX/quiltix.py", line 857, in launch
    editor = QuiltiXWindow()
  File "/home/username/miniconda3/envs/usd/lib/python3.10/site-packages/QuiltiX/quiltix.py", line 62, in __init__
    self.init_ui()
  File "/home/username/miniconda3/envs/usd/lib/python3.10/site-packages/QuiltiX/quiltix.py", line 162, in init_ui
    data_model = StageView.DefaultDataModel()
  File "/home/username/dev/USD/install_dir/USD/lib/python/pxr/Usdviewq/stageView.py", line 684, in __init__
    self._viewSettingsDataModel = ViewSettingsDataModel(self, None)
  File "/home/username/dev/USD/install_dir/USD/lib/python/pxr/Usdviewq/viewSettingsDataModel.py", line 136, in __init__
    QtCore.QObject.__init__(self)
TypeError: StateSource.__init__() missing 2 required positional arguments: 'parent' and 'name'

```

**Comment by lindemeier** [comment]
This is not an issue related to quiltix.
The problem occurs with pyside6 and conflicting at Python modules installed with conda and pi within the same environment.

I fixed it by installing pyside2 and other python modules directly with conda instead of pip in my conda environment.
