### ISSUE TITLE
Downloading the .zip and starting QuiltiX.bat doesn't do anything

### ISSUE THREAD

**Issue by hybridherbst** [PrismPipeline/QuiltiX#84]
I followed the instructions here https://pypi.org/project/QuiltiX/#from-zip to download the complete ZIP archive on Windows.

However, when I run QuiltiX.bat, all it prints is:

```
found Arnold SDK
```

and then it closes again. No window opens or anything.

How can I investigate what's going wrong?

**Version:** QuiltiX_win_v0.6.1

**Comment by RichardFrangenberg** [comment]
Without any error message, the only way to debug that would be to step through the Python code using a debugger (or print statements) to see until which lines of the Python scripts get executed.
The first file which is called is `\tools\entry.py`, which then calls `\python_libs\QuiltiX\quiltix.py`.

**Comment by bperschall** [comment]
I've got the same issue, but I ran the bat file from the CMD shell and see the following:


J:\Temp\QuiltiX_win_v0.6.1>quiltix.bat

J:\Temp\QuiltiX_win_v0.6.1>"J:\Temp\QuiltiX_win_v0.6.1\python/python.exe" "J:\Temp\QuiltiX_win_v0.6.1\tools/entry.py"
found Arnold SDK
Traceback (most recent call last):
  File "J:\Temp\QuiltiX_win_v0.6.1\tools/entry.py", line 25, in <module>
    from QuiltiX import quiltix
  File "J:\Temp\QuiltiX_win_v0.6.1/python_libs\QuiltiX\quiltix.py", line 29, in <module>
    from pxr import UsdShade, Usd
  File "J:\Temp\QuiltiX_win_v0.6.1/python_libs\pxr\UsdShade\__init__.py", line 24, in <module>
    from pxr import Tf
  File "J:\Temp\QuiltiX_win_v0.6.1/python_libs\pxr\Tf\__init__.py", line 178, in <module>
    PreparePythonModule()
  File "J:\Temp\QuiltiX_win_v0.6.1/python_libs\pxr\Tf\__init__.py", line 103, in PreparePythonModule
    module = importlib.import_module(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
ImportError: DLL load failed while importing _tf: The specified procedure could not be found.


Running Windows 10. Any thoughts?

**Comment by benpret** [comment]
Getting the same error:

C:\temp\QuiltiX_win_v0.6.1\QuiltiX_win_v0.6.1>"C:\temp\QuiltiX_win_v0.6.1\QuiltiX_win_v0.6.1\python/python.exe" "C:\temp\QuiltiX_win_v0.6.1\QuiltiX_win_v0.6.1\tools/entry.py"
found Arnold SDK
Traceback (most recent call last):
  File "C:\temp\QuiltiX_win_v0.6.1\QuiltiX_win_v0.6.1\tools/entry.py", line 25, in <module>
    from QuiltiX import quiltix
  File "C:\temp\QuiltiX_win_v0.6.1\QuiltiX_win_v0.6.1/python_libs\QuiltiX\quiltix.py", line 29, in <module>
    from pxr import UsdShade, Usd
  File "C:\temp\QuiltiX_win_v0.6.1\QuiltiX_win_v0.6.1/python_libs\pxr\UsdShade\__init__.py", line 24, in <module>
    from pxr import Tf
  File "C:\temp\QuiltiX_win_v0.6.1\QuiltiX_win_v0.6.1/python_libs\pxr\Tf\__init__.py", line 178, in <module>
    PreparePythonModule()
  File "C:\temp\QuiltiX_win_v0.6.1\QuiltiX_win_v0.6.1/python_libs\pxr\Tf\__init__.py", line 103, in PreparePythonModule
    module = importlib.import_module(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
ImportError: DLL load failed while importing _tf: The specified procedure could not be found.

**Comment by hybridherbst** [comment]
0.8.0 fixes this issue!

**Comment by hybridherbst** [comment]
@bperschall and @benpret, I found a workaround for the ImportError and posted it here: https://github.com/PrismPipeline/QuiltiX/issues/102#issuecomment-3007658535

**Comment by manuelkoester** [comment]
We'll be reuploading a .zip with a fix later so you don't have to apply this on your end manually.  
I'll post another comment when it's up 🙏

**Comment by manuelkoester** [comment]
Uploaded to https://prism-pipeline.com/quiltix! Have fun ❤
