### ISSUE TITLE
Documentation: Instructions for building and running on MacOS

### ISSUE THREAD

**Issue by hybridherbst** [PrismPipeline/QuiltiX#89]
I'm trying to run and/or build QuiltiX on MacOS, however I keep running into the same issue:

```py
Error compiling Cython file:
      ------------------------------------------------------------
      ...
          cdef int PyArray_CheckScalar( object )
          int NPY_ARRAY_CARRAY
          int NPY_ARRAY_FORCECAST
          int PyArray_ISCARRAY( np.ndarray instance )
          int PyArray_ISCARRAY_RO( np.ndarray instance )
          cdef np.ndarray PyArray_Zeros(int nd, np.Py_intptr_t* dims, np.dtype, int fortran)
                                                ^
      ------------------------------------------------------------
      
      src/numpy_formathandler.pyx:22:42: 'Py_intptr_t' is not a type identifier
```

This is on MacPro with Apple M2 Max, MacOS 15.0, but had the same issue in 14.5.

Any help appreciated!

<details>
<summary><b>Show Full Error Message</b> for <code>pip install .</code></summary>

```py
(venv) herbst@Felixs-MacBook-Pro QuiltiX % python3 -m pip install .
Processing /Users/herbst/git/QuiltiX
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pluggy (from QuiltiX==0.6.1)
  Using cached pluggy-1.5.0-py3-none-any.whl.metadata (4.8 kB)
Collecting materialx==1.38.9 (from QuiltiX==0.6.1)
  Using cached materialx-1.38.9-cp312-cp312-macosx_15_0_arm64.whl
Collecting QtPy (from QuiltiX==0.6.1)
  Using cached QtPy-2.4.1-py3-none-any.whl.metadata (12 kB)
Collecting PySide6~=6.6 (from QuiltiX==0.6.1)
  Using cached PySide6-6.7.2-cp39-abi3-macosx_11_0_universal2.whl.metadata (5.3 kB)
Collecting PyOpenGL (from QuiltiX==0.6.1)
  Using cached PyOpenGL-3.1.7-py3-none-any.whl.metadata (3.2 kB)
Collecting PyOpenGL-accelerate (from QuiltiX==0.6.1)
  Using cached PyOpenGL-accelerate-3.1.7.tar.gz (562 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting NodeGraphQt-QuiltiX-fork~=0.7 (from QuiltiX==0.6.1)
  Using cached NodeGraphQt_QuiltiX_fork-0.7.0-py3-none-any.whl.metadata (1.9 kB)
Collecting shiboken6==6.7.2 (from PySide6~=6.6->QuiltiX==0.6.1)
  Using cached shiboken6-6.7.2-cp39-abi3-macosx_11_0_universal2.whl.metadata (2.5 kB)
Collecting PySide6-Essentials==6.7.2 (from PySide6~=6.6->QuiltiX==0.6.1)
  Using cached PySide6_Essentials-6.7.2-cp39-abi3-macosx_11_0_universal2.whl.metadata (3.7 kB)
Collecting PySide6-Addons==6.7.2 (from PySide6~=6.6->QuiltiX==0.6.1)
  Using cached PySide6_Addons-6.7.2-cp39-abi3-macosx_11_0_universal2.whl.metadata (4.0 kB)
Collecting packaging (from QtPy->QuiltiX==0.6.1)
  Using cached packaging-24.1-py3-none-any.whl.metadata (3.2 kB)
Using cached NodeGraphQt_QuiltiX_fork-0.7.0-py3-none-any.whl (121 kB)
Using cached PySide6-6.7.2-cp39-abi3-macosx_11_0_universal2.whl (530 kB)
Using cached PySide6_Addons-6.7.2-cp39-abi3-macosx_11_0_universal2.whl (258.2 MB)
Using cached PySide6_Essentials-6.7.2-cp39-abi3-macosx_11_0_universal2.whl (154.0 MB)
Using cached shiboken6-6.7.2-cp39-abi3-macosx_11_0_universal2.whl (387 kB)
Using cached QtPy-2.4.1-py3-none-any.whl (93 kB)
Downloading pluggy-1.5.0-py3-none-any.whl (20 kB)
Using cached PyOpenGL-3.1.7-py3-none-any.whl (2.4 MB)
Using cached packaging-24.1-py3-none-any.whl (53 kB)
Building wheels for collected packages: QuiltiX, PyOpenGL-accelerate
  Building wheel for QuiltiX (pyproject.toml) ... done
  Created wheel for QuiltiX: filename=QuiltiX-0.6.1-py3-none-any.whl size=16930053 sha256=aa353e9eda77996828c82ec68c23e82e251073a5058be3028e5fb8ecbb60bd04
  Stored in directory: /private/var/folders/9l/jb0_zfsn24l336gr54sgz1640000gn/T/pip-ephem-wheel-cache-r82mi99l/wheels/b0/72/d3/0c27a75ed297916706db4d41bbb971a2bb720a6927780eb87c
  Building wheel for PyOpenGL-accelerate (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for PyOpenGL-accelerate (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [162 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-14.0-arm64-cpython-312
      creating build/lib.macosx-14.0-arm64-cpython-312/OpenGL_accelerate
      copying OpenGL_accelerate/__init__.py -> build/lib.macosx-14.0-arm64-cpython-312/OpenGL_accelerate
      running build_ext
      /private/var/folders/9l/jb0_zfsn24l336gr54sgz1640000gn/T/pip-build-env-nuds1iv9/overlay/lib/python3.12/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /private/var/folders/9l/jb0_zfsn24l336gr54sgz1640000gn/T/pip-install-5o1bsodr/pyopengl-accelerate_50b5f16713b144cfbc2ffe00c035c1ce/OpenGL_accelerate/wrapper.pxd
        tree = Parsing.p_module(s, pxd, full_module_name)
      Compiling src/wrapper.pyx because it changed.
      [1/1] Cythonizing src/wrapper.pyx
      building 'OpenGL_accelerate.wrapper' extension
      creating build/temp.macosx-14.0-arm64-cpython-312
      creating build/temp.macosx-14.0-arm64-cpython-312/src
      clang -fno-strict-overflow -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -I/private/var/folders/9l/jb0_zfsn24l336gr54sgz1640000gn/T/pip-install-5o1bsodr/pyopengl-accelerate_50b5f16713b144cfbc2ffe00c035c1ce/src -I/private/var/folders/9l/jb0_zfsn24l336gr54sgz1640000gn/T/pip-install-5o1bsodr/pyopengl-accelerate_50b5f16713b144cfbc2ffe00c035c1ce -I/Users/herbst/git/QuiltiX/venv/include -I/opt/homebrew/opt/python@3.12/Frameworks/Python.framework/Versions/3.12/include/python3.12 -c src/wrapper.c -o build/temp.macosx-14.0-arm64-cpython-312/src/wrapper.o
      src/wrapper.c:35670:21: warning: fallthrough annotation in unreachable code [-Wunreachable-code-fallthrough]
       35670 |                     CYTHON_FALLTHROUGH;
             |                     ^
      src/wrapper.c:561:34: note: expanded from macro 'CYTHON_FALLTHROUGH'
        561 |       #define CYTHON_FALLTHROUGH __attribute__((fallthrough))
            |                                  ^
      src/wrapper.c:35681:21: warning: fallthrough annotation in unreachable code [-Wunreachable-code-fallthrough]
       35681 |                     CYTHON_FALLTHROUGH;
             |                     ^
      src/wrapper.c:561:34: note: expanded from macro 'CYTHON_FALLTHROUGH'
        561 |       #define CYTHON_FALLTHROUGH __attribute__((fallthrough))
            |                                  ^
      2 warnings generated.
      clang -bundle -undefined dynamic_lookup -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk build/temp.macosx-14.0-arm64-cpython-312/src/wrapper.o -o build/lib.macosx-14.0-arm64-cpython-312/OpenGL_accelerate/wrapper.cpython-312-darwin.so
      /private/var/folders/9l/jb0_zfsn24l336gr54sgz1640000gn/T/pip-build-env-nuds1iv9/overlay/lib/python3.12/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /private/var/folders/9l/jb0_zfsn24l336gr54sgz1640000gn/T/pip-install-5o1bsodr/pyopengl-accelerate_50b5f16713b144cfbc2ffe00c035c1ce/OpenGL_accelerate/formathandler.pxd
        tree = Parsing.p_module(s, pxd, full_module_name)
      Compiling src/formathandler.pyx because it changed.
      [1/1] Cythonizing src/formathandler.pyx
      building 'OpenGL_accelerate.formathandler' extension
      clang -fno-strict-overflow -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -I/private/var/folders/9l/jb0_zfsn24l336gr54sgz1640000gn/T/pip-install-5o1bsodr/pyopengl-accelerate_50b5f16713b144cfbc2ffe00c035c1ce/src -I/private/var/folders/9l/jb0_zfsn24l336gr54sgz1640000gn/T/pip-install-5o1bsodr/pyopengl-accelerate_50b5f16713b144cfbc2ffe00c035c1ce -I/Users/herbst/git/QuiltiX/venv/include -I/opt/homebrew/opt/python@3.12/Frameworks/Python.framework/Versions/3.12/include/python3.12 -c src/formathandler.c -o build/temp.macosx-14.0-arm64-cpython-312/src/formathandler.o
      clang -bundle -undefined dynamic_lookup -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk build/temp.macosx-14.0-arm64-cpython-312/src/formathandler.o -o build/lib.macosx-14.0-arm64-cpython-312/OpenGL_accelerate/formathandler.cpython-312-darwin.so
      /private/var/folders/9l/jb0_zfsn24l336gr54sgz1640000gn/T/pip-build-env-nuds1iv9/overlay/lib/python3.12/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /private/var/folders/9l/jb0_zfsn24l336gr54sgz1640000gn/T/pip-install-5o1bsodr/pyopengl-accelerate_50b5f16713b144cfbc2ffe00c035c1ce/src/arraydatatype.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      Compiling src/arraydatatype.pyx because it changed.
      [1/1] Cythonizing src/arraydatatype.pyx
      building 'OpenGL_accelerate.arraydatatype' extension
      clang -fno-strict-overflow -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -I/private/var/folders/9l/jb0_zfsn24l336gr54sgz1640000gn/T/pip-install-5o1bsodr/pyopengl-accelerate_50b5f16713b144cfbc2ffe00c035c1ce/src -I/private/var/folders/9l/jb0_zfsn24l336gr54sgz1640000gn/T/pip-install-5o1bsodr/pyopengl-accelerate_50b5f16713b144cfbc2ffe00c035c1ce -I/Users/herbst/git/QuiltiX/venv/include -I/opt/homebrew/opt/python@3.12/Frameworks/Python.framework/Versions/3.12/include/python3.12 -c src/arraydatatype.c -o build/temp.macosx-14.0-arm64-cpython-312/src/arraydatatype.o
      clang -bundle -undefined dynamic_lookup -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk build/temp.macosx-14.0-arm64-cpython-312/src/arraydatatype.o -o build/lib.macosx-14.0-arm64-cpython-312/OpenGL_accelerate/arraydatatype.cpython-312-darwin.so
      /private/var/folders/9l/jb0_zfsn24l336gr54sgz1640000gn/T/pip-build-env-nuds1iv9/overlay/lib/python3.12/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /private/var/folders/9l/jb0_zfsn24l336gr54sgz1640000gn/T/pip-install-5o1bsodr/pyopengl-accelerate_50b5f16713b144cfbc2ffe00c035c1ce/src/errorchecker.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      Compiling src/errorchecker.pyx because it changed.
      [1/1] Cythonizing src/errorchecker.pyx
      building 'OpenGL_accelerate.errorchecker' extension
      clang -fno-strict-overflow -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -I/private/var/folders/9l/jb0_zfsn24l336gr54sgz1640000gn/T/pip-install-5o1bsodr/pyopengl-accelerate_50b5f16713b144cfbc2ffe00c035c1ce/src -I/private/var/folders/9l/jb0_zfsn24l336gr54sgz1640000gn/T/pip-install-5o1bsodr/pyopengl-accelerate_50b5f16713b144cfbc2ffe00c035c1ce -I/Users/herbst/git/QuiltiX/venv/include -I/opt/homebrew/opt/python@3.12/Frameworks/Python.framework/Versions/3.12/include/python3.12 -c src/errorchecker.c -o build/temp.macosx-14.0-arm64-cpython-312/src/errorchecker.o
      clang -bundle -undefined dynamic_lookup -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk build/temp.macosx-14.0-arm64-cpython-312/src/errorchecker.o -o build/lib.macosx-14.0-arm64-cpython-312/OpenGL_accelerate/errorchecker.cpython-312-darwin.so
      /private/var/folders/9l/jb0_zfsn24l336gr54sgz1640000gn/T/pip-build-env-nuds1iv9/overlay/lib/python3.12/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /private/var/folders/9l/jb0_zfsn24l336gr54sgz1640000gn/T/pip-install-5o1bsodr/pyopengl-accelerate_50b5f16713b144cfbc2ffe00c035c1ce/src/vbo.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      Compiling src/vbo.pyx because it changed.
      [1/1] Cythonizing src/vbo.pyx
      building 'OpenGL_accelerate.vbo' extension
      clang -fno-strict-overflow -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -I/private/var/folders/9l/jb0_zfsn24l336gr54sgz1640000gn/T/pip-install-5o1bsodr/pyopengl-accelerate_50b5f16713b144cfbc2ffe00c035c1ce/src -I/private/var/folders/9l/jb0_zfsn24l336gr54sgz1640000gn/T/pip-install-5o1bsodr/pyopengl-accelerate_50b5f16713b144cfbc2ffe00c035c1ce -I/Users/herbst/git/QuiltiX/venv/include -I/opt/homebrew/opt/python@3.12/Frameworks/Python.framework/Versions/3.12/include/python3.12 -c src/vbo.c -o build/temp.macosx-14.0-arm64-cpython-312/src/vbo.o
      clang -bundle -undefined dynamic_lookup -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk build/temp.macosx-14.0-arm64-cpython-312/src/vbo.o -o build/lib.macosx-14.0-arm64-cpython-312/OpenGL_accelerate/vbo.cpython-312-darwin.so
      /private/var/folders/9l/jb0_zfsn24l336gr54sgz1640000gn/T/pip-build-env-nuds1iv9/overlay/lib/python3.12/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /private/var/folders/9l/jb0_zfsn24l336gr54sgz1640000gn/T/pip-install-5o1bsodr/pyopengl-accelerate_50b5f16713b144cfbc2ffe00c035c1ce/src/nones_formathandler.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      Compiling src/nones_formathandler.pyx because it changed.
      [1/1] Cythonizing src/nones_formathandler.pyx
      building 'OpenGL_accelerate.nones_formathandler' extension
      clang -fno-strict-overflow -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -I/private/var/folders/9l/jb0_zfsn24l336gr54sgz1640000gn/T/pip-install-5o1bsodr/pyopengl-accelerate_50b5f16713b144cfbc2ffe00c035c1ce/src -I/private/var/folders/9l/jb0_zfsn24l336gr54sgz1640000gn/T/pip-install-5o1bsodr/pyopengl-accelerate_50b5f16713b144cfbc2ffe00c035c1ce -I/Users/herbst/git/QuiltiX/venv/include -I/opt/homebrew/opt/python@3.12/Frameworks/Python.framework/Versions/3.12/include/python3.12 -c src/nones_formathandler.c -o build/temp.macosx-14.0-arm64-cpython-312/src/nones_formathandler.o
      clang -bundle -undefined dynamic_lookup -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk build/temp.macosx-14.0-arm64-cpython-312/src/nones_formathandler.o -o build/lib.macosx-14.0-arm64-cpython-312/OpenGL_accelerate/nones_formathandler.cpython-312-darwin.so
      /private/var/folders/9l/jb0_zfsn24l336gr54sgz1640000gn/T/pip-build-env-nuds1iv9/overlay/lib/python3.12/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /private/var/folders/9l/jb0_zfsn24l336gr54sgz1640000gn/T/pip-install-5o1bsodr/pyopengl-accelerate_50b5f16713b144cfbc2ffe00c035c1ce/src/latebind.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      Compiling src/latebind.pyx because it changed.
      [1/1] Cythonizing src/latebind.pyx
      building 'OpenGL_accelerate.latebind' extension
      clang -fno-strict-overflow -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -I/private/var/folders/9l/jb0_zfsn24l336gr54sgz1640000gn/T/pip-install-5o1bsodr/pyopengl-accelerate_50b5f16713b144cfbc2ffe00c035c1ce/src -I/private/var/folders/9l/jb0_zfsn24l336gr54sgz1640000gn/T/pip-install-5o1bsodr/pyopengl-accelerate_50b5f16713b144cfbc2ffe00c035c1ce -I/Users/herbst/git/QuiltiX/venv/include -I/opt/homebrew/opt/python@3.12/Frameworks/Python.framework/Versions/3.12/include/python3.12 -c src/latebind.c -o build/temp.macosx-14.0-arm64-cpython-312/src/latebind.o
      src/latebind.c:2916:12: warning: unused function '__pyx_pw_17OpenGL_accelerate_8latebind_8LateBind_5__nonzero__' [-Wunused-function]
       2916 | static int __pyx_pw_17OpenGL_accelerate_8latebind_8LateBind_5__nonzero__(PyObject *__pyx_v_self) {
            |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      1 warning generated.
      clang -bundle -undefined dynamic_lookup -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk build/temp.macosx-14.0-arm64-cpython-312/src/latebind.o -o build/lib.macosx-14.0-arm64-cpython-312/OpenGL_accelerate/latebind.cpython-312-darwin.so
      /private/var/folders/9l/jb0_zfsn24l336gr54sgz1640000gn/T/pip-build-env-nuds1iv9/overlay/lib/python3.12/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /private/var/folders/9l/jb0_zfsn24l336gr54sgz1640000gn/T/pip-install-5o1bsodr/pyopengl-accelerate_50b5f16713b144cfbc2ffe00c035c1ce/src/buffers_formathandler.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      Compiling src/buffers_formathandler.pyx because it changed.
      [1/1] Cythonizing src/buffers_formathandler.pyx
      building 'OpenGL_accelerate.buffers_formathandler' extension
      clang -fno-strict-overflow -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -I/private/var/folders/9l/jb0_zfsn24l336gr54sgz1640000gn/T/pip-install-5o1bsodr/pyopengl-accelerate_50b5f16713b144cfbc2ffe00c035c1ce/src -I/private/var/folders/9l/jb0_zfsn24l336gr54sgz1640000gn/T/pip-install-5o1bsodr/pyopengl-accelerate_50b5f16713b144cfbc2ffe00c035c1ce -I/Users/herbst/git/QuiltiX/venv/include -I/opt/homebrew/opt/python@3.12/Frameworks/Python.framework/Versions/3.12/include/python3.12 -c src/buffers_formathandler.c -o build/temp.macosx-14.0-arm64-cpython-312/src/buffers_formathandler.o
      clang -bundle -undefined dynamic_lookup -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk build/temp.macosx-14.0-arm64-cpython-312/src/buffers_formathandler.o -o build/lib.macosx-14.0-arm64-cpython-312/OpenGL_accelerate/buffers_formathandler.cpython-312-darwin.so
      /private/var/folders/9l/jb0_zfsn24l336gr54sgz1640000gn/T/pip-build-env-nuds1iv9/overlay/lib/python3.12/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /private/var/folders/9l/jb0_zfsn24l336gr54sgz1640000gn/T/pip-install-5o1bsodr/pyopengl-accelerate_50b5f16713b144cfbc2ffe00c035c1ce/src/numpy_formathandler.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          cdef int PyArray_CheckScalar( object )
          int NPY_ARRAY_CARRAY
          int NPY_ARRAY_FORCECAST
          int PyArray_ISCARRAY( np.ndarray instance )
          int PyArray_ISCARRAY_RO( np.ndarray instance )
          cdef np.ndarray PyArray_Zeros(int nd, np.Py_intptr_t* dims, np.dtype, int fortran)
                                                ^
      ------------------------------------------------------------
      
      src/numpy_formathandler.pyx:22:42: 'Py_intptr_t' is not a type identifier
      Compiling src/numpy_formathandler.pyx because it changed.
      [1/1] Cythonizing src/numpy_formathandler.pyx
      Traceback (most recent call last):
        File "/Users/herbst/git/QuiltiX/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/herbst/git/QuiltiX/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/herbst/git/QuiltiX/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/9l/jb0_zfsn24l336gr54sgz1640000gn/T/pip-build-env-nuds1iv9/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 415, in build_wheel
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/9l/jb0_zfsn24l336gr54sgz1640000gn/T/pip-build-env-nuds1iv9/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 397, in _build_with_temp_dir
          self.run_setup()
        File "/private/var/folders/9l/jb0_zfsn24l336gr54sgz1640000gn/T/pip-build-env-nuds1iv9/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 113, in <module>
        File "/private/var/folders/9l/jb0_zfsn24l336gr54sgz1640000gn/T/pip-build-env-nuds1iv9/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/9l/jb0_zfsn24l336gr54sgz1640000gn/T/pip-build-env-nuds1iv9/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/9l/jb0_zfsn24l336gr54sgz1640000gn/T/pip-build-env-nuds1iv9/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/private/var/folders/9l/jb0_zfsn24l336gr54sgz1640000gn/T/pip-build-env-nuds1iv9/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 970, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/9l/jb0_zfsn24l336gr54sgz1640000gn/T/pip-build-env-nuds1iv9/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 956, in run_command
          super().run_command(command)
        File "/private/var/folders/9l/jb0_zfsn24l336gr54sgz1640000gn/T/pip-build-env-nuds1iv9/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
          cmd_obj.run()
        File "/private/var/folders/9l/jb0_zfsn24l336gr54sgz1640000gn/T/pip-build-env-nuds1iv9/overlay/lib/python3.12/site-packages/setuptools/command/bdist_wheel.py", line 373, in run
          self.run_command("build")
        File "/private/var/folders/9l/jb0_zfsn24l336gr54sgz1640000gn/T/pip-build-env-nuds1iv9/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/9l/jb0_zfsn24l336gr54sgz1640000gn/T/pip-build-env-nuds1iv9/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 956, in run_command
          super().run_command(command)
        File "/private/var/folders/9l/jb0_zfsn24l336gr54sgz1640000gn/T/pip-build-env-nuds1iv9/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
          cmd_obj.run()
        File "/private/var/folders/9l/jb0_zfsn24l336gr54sgz1640000gn/T/pip-build-env-nuds1iv9/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/private/var/folders/9l/jb0_zfsn24l336gr54sgz1640000gn/T/pip-build-env-nuds1iv9/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/9l/jb0_zfsn24l336gr54sgz1640000gn/T/pip-build-env-nuds1iv9/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 956, in run_command
          super().run_command(command)
        File "/private/var/folders/9l/jb0_zfsn24l336gr54sgz1640000gn/T/pip-build-env-nuds1iv9/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
          cmd_obj.run()
        File "/private/var/folders/9l/jb0_zfsn24l336gr54sgz1640000gn/T/pip-build-env-nuds1iv9/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
          self.build_extensions()
        File "/private/var/folders/9l/jb0_zfsn24l336gr54sgz1640000gn/T/pip-build-env-nuds1iv9/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/build_ext.py", line 479, in build_extensions
          self._build_extensions_serial()
        File "/private/var/folders/9l/jb0_zfsn24l336gr54sgz1640000gn/T/pip-build-env-nuds1iv9/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/build_ext.py", line 505, in _build_extensions_serial
          self.build_extension(ext)
        File "/private/var/folders/9l/jb0_zfsn24l336gr54sgz1640000gn/T/pip-build-env-nuds1iv9/overlay/lib/python3.12/site-packages/Cython/Distutils/build_ext.py", line 130, in build_extension
          new_ext = cythonize(
                    ^^^^^^^^^^
        File "/private/var/folders/9l/jb0_zfsn24l336gr54sgz1640000gn/T/pip-build-env-nuds1iv9/overlay/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
          cythonize_one(*args)
        File "/private/var/folders/9l/jb0_zfsn24l336gr54sgz1640000gn/T/pip-build-env-nuds1iv9/overlay/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: src/numpy_formathandler.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for PyOpenGL-accelerate
Successfully built QuiltiX
Failed to build PyOpenGL-accelerate
ERROR: Could not build wheels for PyOpenGL-accelerate, which is required to install pyproject.toml-based projects
```
</details>

**Comment by RichardFrangenberg** [comment]
I don't have a Mac to test it, but the issue seems to be that installing PyOpenGL-accelerate fails, which would be unrelated to QuiltiX.
Can you try to run `pip install PyOpenGL-accelerate` in your terminal to see if that gives the same error?

**Comment by hybridherbst** [comment]
I see, thank you. After searching a bit more, PyOpenGL-accelerate seems to not install on Macs at all on Python 3.6+ (with QuiltiX requiring 3.11) (https://github.com/p5py/p5/issues/439). Not sure how to get QuiltiX to run on Mac then!

**Comment by RichardFrangenberg** [comment]
You can try to remove "PyOpenGL_accelerate" from the `pyproject.toml` file in the QuiltiX root folder. I think this is just an optional dependency.
