### ISSUE TITLE
pixi setup: Pre-built python version of OpenUSD_build

### ISSUE THREAD

**Issue by jo-chemla** [PrismPipeline/QuiltiX#96]
Hi there, 

I'm trying to use QulitiX with pixi and am having the following error trying to run it:  `ImportError: DLL load failed while importing _usd: The specified procedure could not be found`. The root readme states that QuiltiX requires python 3.11+ to run, and I could not find which python version is used for the pre-built [PrismPipeline/OpenUSD_build](https://github.com/PrismPipeline/OpenUSD_build/tree/24.03-win-mtlx-1.38.9) but I assume it's the same - some older threads like [this one](https://github.com/PrismPipeline/QuiltiX/issues/25) or [this one](https://github.com/PrismPipeline/QuiltiX/issues/42) mentioned python 3.9. Or do I need to build it myself and link it as shown in the doc [using-your-own-compiled-openusd](https://github.com/PrismPipeline/QuiltiX?tab=readme-ov-file#using-your-own-compiled-openusd)? 

Would love some pointer in case you have some!

Here is my `pixi.toml` file

```toml

[project]
authors = ["Jonathan "]
channels = ["conda-forge"]
description = "Add a short description here"
name = "quiltx"
platforms = ["win-64"]
version = "0.1.0"

# conda dependencies
[dependencies]
python = "3.11.*"
 
# extra dependencies from PyPI
[pypi-dependencies]
QuiltiX = "*"
OpenUSD_build = { git = "https://github.com/PrismPipeline/OpenUSD_build.git", branch = "24.03-win-mtlx-1.38.9" }

[tasks]
badQuiltiX = "python -m QuiltiX"
goodQuiltiX = { cmd = "python -m QuiltiX", env = { PATH = "$CONDA_PREFIX\\Lib\\site-packages\\pxr\\lib;$CONDA_PREFIX\\Lib\\site-packages\\pxr\\bin;$PATH" } }

```

[edit]: modified the `badQuiltiX` with `goodQuiltiX` above which does work

And error log: 

```bash
C:\Users\jonathan\Downloads\quiltx\quiltx>pixi run QuiltiX
✨ Pixi task (QuiltiX): python -m QuiltiX
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\jonathan\Downloads\quiltx\quiltx\.pixi\envs\default\Lib\site-packages\QuiltiX\__main__.py", line 1, in <module>
    from . import quiltix
  File "C:\Users\jonathan\Downloads\quiltx\quiltx\.pixi\envs\default\Lib\site-packages\QuiltiX\quiltix.py", line 25, in <module>
    from pxr import Usd, UsdShade
  File "C:\Users\jonathan\Downloads\quiltx\quiltx\.pixi\envs\default\Lib\site-packages\pxr\Usd\__init__.py", line 25, in <module>
    Tf.PreparePythonModule()
  File "C:\Users\jonathan\Downloads\quiltx\quiltx\.pixi\envs\default\Lib\site-packages\pxr\Tf\__init__.py", line 103, in PreparePythonModule
    module = importlib.import_module(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonathan\Downloads\quiltx\quiltx\.pixi\envs\default\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: DLL load failed while importing _usd: The specified procedure could not be found.
```

PS when using python 3.9.x in pixi dependencies, I get the following error which suggest QuiltiX does require indeed 3.11 `ImportError: Module use of python311.dll conflicts with this version of Python`

**Comment by jo-chemla** [comment]
Edit: Got it working with this `pixi task`, setting environment variables to point where dlls have been installed by pixi: 

```toml
[tasks]
QuiltiX = { cmd = "python -m QuiltiX", env = { PATH = "C:\\Users\\jonathan\\Downloads\\quiltx\\quiltx\\.pixi\\envs\\default\\Lib\\site-packages\\pxr\\lib;C:\\Users\\jonathan\\Downloads\\quiltx\\quiltx\\.pixi\\envs\\default\\Lib\\site-packages\\pxr\\bin;$PATH" } }

```
